site_name: Witnet-rust Documentation
site_url: https://docs.witnet.io
copyright: Â© 2018 Witnet Foundation. Available under <a href="https://www.gnu.org/licenses/fdl-1.3.en.html" rel="license">GNU Free Documentation License v1.3</a>

docs_dir: docs

nav:
  - Home: index.md
  - Get started:
    - What is Witnet: get-started/what-is-witnet
    - Why Rust?: get-started/why-rust
    - Design Overview: get-started/design-overview
    - Install: get-started/install
  - Protocol:
    - Network messages: protocol/network
    - Network objects:
      - Data requests: protocol/data-requests
      - Transactions: protocol/transactions
      - Blocks: protocol/blocks
    - Reputation: protocol/reputation
    - Mining: protocol/mining
    - Task assignment: protocol/task-assignment
    - WitScript: protocol/witscript
  - Architecture:
    - Overview: architecture/overview
    - Peer-To-Peer:
      - Connections: architecture/p2p/connections
      - Gossiping: architecture/p2p/gossip
      - Encoding (FlatBuffers): architecture/p2p/encoding
    - Storage: architecture/storage
    - Mempool Management: architecture/mempool-mgmt
    - Block Management: architecture/block-mgmt
    - UTXO Management: architecture/utxo-mgmt
    - Data Requests:
      - Overview: architecture/rad/overview
      - Headless Browser Engine: architecture/rad/hbe
      - retrieve.js: architecture/rad/retrieve-js
      - RadLang: architecture/rad/radlang
    - Witscript Parser: architecture/witscript
  - Advanced:
    - Network constants: advanced/constants
    - Differences with the whitepaper: advanced/whitepaper-differences
  - Roadmap: roadmap
  - Contributing: contributing
  - Glossary: glossary

theme:
  name: 'material'
  favicon: 'assets/images/favicon.ico'
  logo: 'assets/images/logo.svg" alt="Witnet Logo'
  palette:
    primary: 'indigo'
    accent: 'deep purple'

repo_name: 'witnet/witnet-rust'
repo_url: 'https://github.com/witnet/witnet-rust'
edit_uri: 'blob/master/docs'
remote_name: 'upstream'

extra:
  og_image: 'assets/images/logo-docs.png'
  social:
    - type: 'github'
      link: 'https://github.com/witnet'
    - type: 'reddit'
      link: 'https://reddit.com/r/witnet'
    - type: 'twitter'
      link: 'https://twitter.com/witnet_io'

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
