# Address of the witnet node JSON-RPC server
witnet_jsonrpc_addr = "127.0.0.1:21336"
# Url of the ethereum client
eth_client_url = "http://127.0.0.1:8545"
# Address of the WitnetRequestsBoard deployed contract
wrb_contract_addr = "0xCF8B9f0Edc298Da2CD5832Dc9D85D805E33dB5Af"
# Address of the BlockRelay deployed contract
block_relay_contract_addr = "0xEaA9e7Ea612b169f5b41cfF86dA6322f57264a19"
# Ethereum account used to create the transactions
eth_account = "0xa550Cf4F03Bd2417Cf83c8a652703cdC33c016ee"
# Period to check for new requests in the WRB
eth_new_dr_polling_rate_ms = 1_000
wit_tally_polling_rate_ms = 45000
wit_dr_sender_polling_rate_ms = 45000

# Running in the witnet testnet?
witnet_testnet = true

# Gas limits for some methods.
# To let the client estimate, comment out the fields
[gas_limits]
post_data_request = 10000000
report_result = 2000000
