# Address of the witnet node JSON-RPC server
witnet_jsonrpc_addr = "127.0.0.1:1233"
# Url of the ethereum client
eth_client_url = "http://127.0.0.1:8545"
# Address of the WitnetBridgeInterface deployed contract
wbi_contract_addr = "0xc408f2534b64f641b27f17372042937762829dAe"
# Address of the BlockRelay deployed contract
block_relay_contract_addr = "0x59053ACa5E548636F0B0e78eAf36De812f939E9d"
# Ethereum account used to create the transactions
eth_account = "0x33Cb9179aF22b4C0392b1E2C651e233E894E48Ff"
# Enable block relay from witnet to ethereum?
enable_block_relay = true
# Post data request more than once? Useful to retry if the data request
# was not included in a block
post_to_witnet_more_than_once = true
# Subscribe to witnet blocks? This is only necessary for block relay
subscribe_to_witnet_blocks = true
